import { Router } from 'express';
import { createOrderReport, getOrderReports, getOrderReportById, updateOrderReportStatus, deleteOrderReport } from '../controllers/orderReportController';
import { authAndRefresh } from '../utils/jwt';

const router = Router();

/**
 * @swagger
 * /order-reports:
 *   post:
 *     summary: Create Order Report
 *     tags: [Order Reports]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - title
 *               - description
 *               - orderId
 *               - assignedTo
 *               - disposalQuantity
 *             properties:
 *               title:
 *                 type: string
 *                 description: Report title
 *               description:
 *                 type: string
 *                 description: Report description
 *               orderId:
 *                 type: string
 *                 description: Order ID
 *               assignedTo:
 *                 type: string
 *                 description: Assigned regulatory user ID
 *               disposalQuantity:
 *                 type: number
 *                 description: Disposal quantity
 *               disposalMethod:
 *                 type: string
 *                 description: Disposal method (optional)
 *               evidenceLinks:
 *                 type: array
 *                 description: Evidence links (e.g., Google Drive/OneDrive URLs)
 *                 items:
 *                   type: string
 *                   format: uri
 *               materials:
 *                 type: array
 *                 description: Material details (optional)
 *                 items:
 *                   type: object
 *                   properties:
 *                     materialKey:
 *                       type: string
 *                     wasteStreamClassification:
 *                       type: array
 *                       items:
 *                         type: string
 *                     labellingAndPackaging:
 *                       type: array
 *                       items:
 *                         type: string
 *                     transportationAndStorage:
 *                       type: string
 *                     condition:
 *                       type: array
 *                       items:
 *                         type: string
 *                     disposalMethod:
 *                       type: array
 *                       items:
 *                         type: string
 *                     attachments:
 *                       type: array
 *                       items:
 *                         type: object
 *                         properties:
 *                           fileId:
 *                             type: string
 *                           fileName:
 *                             type: string
 *                           mimeType:
 *                             type: string
 *               notes:
 *                 type: string
 *                 description: Notes (optional)
 *               submittedAt:
 *                 type: string
 *                 format: date-time
 *                 description: Submission time (auto-generated by backend, frontend input will be ignored)
 *     responses:
 *       201:
 *         description: Order report created successfully
 *       400:
 *         description: Invalid request parameters
 *       401:
 *         description: Unauthorized
 *       500:
 *         description: Server error
 */
router.post('/', authAndRefresh, createOrderReport);

/**
 * @swagger
 * /order-reports:
 *   get:
 *     summary: Get Order Reports List (with filtering, pagination, search)
 *     tags: [Order Reports]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: page
 *         schema:
 *           type: integer
 *           default: 1
 *         description: Page number
 *       - in: query
 *         name: limit
 *         schema:
 *           type: integer
 *           default: 10
 *         description: Items per page
 *       - in: query
 *         name: search
 *         schema:
 *           type: string
 *         description: Search keywords (title, description)
 *       - in: query
 *         name: status
 *         schema:
 *           type: string
 *           enum: [pending, approved, rejected]
 *         description: Report status filter
 *       - in: query
 *         name: sortBy
 *         schema:
 *           type: string
 *           enum: [createdAt, updatedAt, title, status]
 *           default: createdAt
 *         description: Sort field
 *       - in: query
 *         name: sortOrder
 *         schema:
 *           type: string
 *           enum: [asc, desc]
 *           default: desc
 *         description: Sort order
 *     responses:
 *       200:
 *         description: Successfully retrieved order reports list
 *       401:
 *         description: Unauthorized
 *       500:
 *         description: Server error
 */
router.get('/', authAndRefresh, getOrderReports);

/**
 * @swagger
 * /order-reports/{id}:
 *   get:
 *     summary: Get Single Order Report Details
 *     tags: [Order Reports]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Report ID
 *     responses:
 *       200:
 *         description: Successfully retrieved order report details
 *       401:
 *         description: Unauthorized
 *       403:
 *         description: Insufficient permissions
 *       404:
 *         description: Report not found
 *       500:
 *         description: Server error
 */
router.get('/:id', authAndRefresh, getOrderReportById);

/**
 * @swagger
 * /order-reports/{id}/status:
 *   patch:
 *     summary: Update Order Report Status
 *     tags: [Order Reports]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Report ID
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - status
 *             properties:
 *               status:
 *                 type: string
 *                 enum: [pending, approved, rejected]
 *                 description: New status
 *               comment:
 *                 type: string
 *                 description: Optional comment
 *     responses:
 *       200:
 *         description: Status updated successfully
 *       400:
 *         description: Invalid request parameters
 *       401:
 *         description: Unauthorized
 *       403:
 *         description: Insufficient permissions - only assigned regulatory user or admin can update status
 *       404:
 *         description: Report not found
 *       500:
 *         description: Server error
 */
router.patch('/:id/status', authAndRefresh, updateOrderReportStatus);

/**
 * @swagger
 * /order-reports/{id}:
 *   delete:
 *     summary: Delete Order Report
 *     tags: [Order Reports]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Report ID
 *     responses:
 *       200:
 *         description: Order report deleted successfully
 *       401:
 *         description: Unauthorized
 *       403:
 *         description: Insufficient permissions
 *       404:
 *         description: Report not found
 *       500:
 *         description: Server error
 */
router.delete('/:id', authAndRefresh, deleteOrderReport);

export default router; 