import { Request, Response } from 'express';
import OrderReport, { IOrderReport } from '../models/OrderReport';
import Order from '../models/Order';
import User from '../models/User';
import { updateOrderStatus } from './orderController';

interface RequestWithUser extends Request {
  user?: { id: string; email: string; role: string };
}

// Create order report
// POST /order-reports
export const createOrderReport = async (req: RequestWithUser, res: Response) => {
  try {
    const { title, description, orderId, assignedTo, disposalQuantity, disposalMethod, evidenceLinks, materials, notes } = req.body;
    const userId = (req as any).user?.id;

    if (!userId) {
      return res.status(401).json({ success: false, error: 'Unauthorized' });
    }

    // Validate required fields
    if (!title || !description || !orderId || !assignedTo || !disposalQuantity) {
      return res.status(400).json({ 
        success: false, 
        error: 'Missing required fields: title, description, orderId, assignedTo, disposalQuantity' 
      });
    }

    // Check if assigned user exists and is a regulator
    const assignedUser = await User.findById(assignedTo);
    if (!assignedUser) {
      return res.status(400).json({ 
        success: false, 
        error: 'Assigned user not found' 
      });
    }

    if (assignedUser.role !== 'regulator') {
      return res.status(400).json({ 
        success: false, 
        error: 'Assigned user must be a regulator' 
      });
    }

    // Check if order exists
    const order = await Order.findById(orderId);
    if (!order) {
      return res.status(400).json({ 
        success: false, 
        error: 'Order not found' 
      });
    }

    // Check if disposal quantity is reasonable
    if (disposalQuantity > order.producedQuantity) {
      return res.status(400).json({ 
        success: false, 
        error: 'Disposal quantity cannot exceed produced quantity' 
      });
    }

    // Check if disposal quantity exceeds available quantity (inUseQuantity + unusedQuantity)
    const availableForDisposal = order.inUseQuantity + order.unusedQuantity;
    if (disposalQuantity > availableForDisposal) {
      return res.status(400).json({ 
        success: false, 
        error: `Disposal quantity (${disposalQuantity}) cannot exceed available quantity (${availableForDisposal})` 
      });
    }

    // Process evidenceLinks (optional)
    let sanitizedEvidenceLinks: string[] | undefined = undefined;
    if (Array.isArray(evidenceLinks)) {
      sanitizedEvidenceLinks = evidenceLinks
        .filter((v: any) => typeof v === 'string')
        .map((v: string) => v.trim())
        .filter((v: string) => v.length > 0);
    }

    // Process materials (optional)
    let sanitizedMaterials: any[] | undefined = undefined;
    if (Array.isArray(materials)) {
      sanitizedMaterials = materials.map((m: any) => ({
        materialKey: typeof m?.materialKey === 'string' ? m.materialKey.trim() : '',
        wasteStreamClassification: Array.isArray(m?.wasteStreamClassification) ? m.wasteStreamClassification.filter((x: any) => typeof x === 'string' && x.trim() !== '') : [],
        labellingAndPackaging: Array.isArray(m?.labellingAndPackaging) ? m.labellingAndPackaging.filter((x: any) => typeof x === 'string' && x.trim() !== '') : [],
        transportationAndStorage: typeof m?.transportationAndStorage === 'string' ? m.transportationAndStorage.trim() : '',
        condition: Array.isArray(m?.condition) ? m.condition.filter((x: any) => typeof x === 'string' && x.trim() !== '') : [],
        disposalMethod: Array.isArray(m?.disposalMethod) ? m.disposalMethod.filter((x: any) => typeof x === 'string' && x.trim() !== '') : [],
        attachments: Array.isArray(m?.attachments) ? m.attachments.filter((a: any) => a && typeof a.fileId === 'string' && typeof a.fileName === 'string' && typeof a.mimeType === 'string').map((a: any) => ({
          fileId: a.fileId.trim(),
          fileName: a.fileName.trim(),
          mimeType: a.mimeType.trim()
        })) : []
      })).filter((mm: any) => mm.materialKey !== '');
      if (sanitizedMaterials.length === 0) sanitizedMaterials = undefined;
    }

                // Create report (submittedAt generated by backend)
      console.log(`[DEBUG] Creating order report`);
      const report = await OrderReport.create({
        title,
        description,
        orderId,
        assignedTo,
        createdBy: userId,
        disposalQuantity,
        disposalMethod,
        ...(sanitizedEvidenceLinks ? { evidenceLinks: sanitizedEvidenceLinks } : {}),
        ...(sanitizedMaterials ? { materials: sanitizedMaterials } : {}),
        ...(typeof notes === 'string' && notes.trim() !== '' ? { notes: notes.trim() } : {}),
        submittedAt: new Date()
      });

      // Directly update order disposal quantity
      console.log(`[DEBUG] Directly updating order ${orderId} with disposalQuantity: ${disposalQuantity}`);
      
              // Re-query order to ensure data is up to date
      const currentOrder = await Order.findById(orderId);
      if (!currentOrder) {
        return res.status(404).json({ success: false, error: 'Order not found' });
      }

      console.log(`[DEBUG] Current order state:`, {
        status: currentOrder.status,
        inUseQuantity: currentOrder.inUseQuantity,
        disposedQuantity: currentOrder.disposedQuantity,
        unusedQuantity: currentOrder.unusedQuantity,
        producedQuantity: currentOrder.producedQuantity
      });

              // Check if quantity sum is correct
      const currentTotal = currentOrder.inUseQuantity + currentOrder.disposedQuantity + currentOrder.unusedQuantity;
      console.log(`[DEBUG] Current total: ${currentTotal}, should equal: ${currentOrder.producedQuantity}`);
      
      if (currentTotal !== currentOrder.producedQuantity) {
        console.error(`[DEBUG] Quantity mismatch! Current total: ${currentTotal}, produced: ${currentOrder.producedQuantity}`);
        return res.status(400).json({ 
          success: false, 
          error: `Order quantity mismatch: total (${currentTotal}) != produced (${currentOrder.producedQuantity})` 
        });
      }

              // Directly update quantities - prioritize disposal from inUseQuantity, then from unusedQuantity
      const newDisposedQuantity = currentOrder.disposedQuantity + disposalQuantity;
      
      let newInUseQuantity = currentOrder.inUseQuantity;
      let newUnusedQuantity = currentOrder.unusedQuantity;
      
              // Prioritize disposal from inUseQuantity
      if (currentOrder.inUseQuantity >= disposalQuantity) {
        newInUseQuantity = currentOrder.inUseQuantity - disposalQuantity;
      } else {
        // If inUseQuantity is insufficient, dispose remaining from unusedQuantity
        const remainingFromUnused = disposalQuantity - currentOrder.inUseQuantity;
        newInUseQuantity = 0;
        newUnusedQuantity = currentOrder.unusedQuantity - remainingFromUnused;
      }
      
      console.log(`[DEBUG] Updating quantities:`, {
        disposedQuantity: `${currentOrder.disposedQuantity} -> ${newDisposedQuantity}`,
        inUseQuantity: `${currentOrder.inUseQuantity} -> ${newInUseQuantity}`,
        unusedQuantity: `${currentOrder.unusedQuantity} -> ${newUnusedQuantity}`
      });
      
      currentOrder.disposedQuantity = newDisposedQuantity;
      currentOrder.inUseQuantity = newInUseQuantity;
      currentOrder.unusedQuantity = newUnusedQuantity;
      currentOrder.updatedAt = new Date();
      
      console.log(`[DEBUG] After update:`, {
        inUseQuantity: currentOrder.inUseQuantity,
        disposedQuantity: currentOrder.disposedQuantity,
        unusedQuantity: currentOrder.unusedQuantity,
        producedQuantity: currentOrder.producedQuantity,
        newTotal: currentOrder.inUseQuantity + currentOrder.disposedQuantity + currentOrder.unusedQuantity
      });

              // Save to database
      try {
        await currentOrder.save();
        console.log(`[DEBUG] Order saved successfully`);
      } catch (saveError) {
        console.error(`[DEBUG] Save error:`, saveError);
        return res.status(400).json({ 
          success: false, 
          error: `Failed to save order: ${saveError.message}` 
        });
      }

              // Return detailed information
      const populatedReport = await OrderReport.findById(report._id)
        .populate('assignedTo', 'firstName lastName email role')
        .populate('createdBy', 'firstName lastName email role')
        .populate('orderId', 'batchNumber status producedQuantity inUseQuantity disposedQuantity unusedQuantity');

      res.status(201).json({
        success: true,
        data: populatedReport,
        message: 'Order report created successfully'
      });
  } catch (err) {
    console.error('Create order report error:', err);
    res.status(500).json({ success: false, error: 'Server error' });
  }
};

// Get order report list
// GET /order-reports
export const getOrderReports = async (req: RequestWithUser, res: Response) => {
  try {
    const userId = (req as any).user?.id;
    if (!userId) {
      
      return res.status(401).json({ success: false, error: 'Unauthorized' });
    }

    // Get query parameters
    const page = parseInt(req.query.page as string) || 1;
    const limit = parseInt(req.query.limit as string) || 10;
    const search = req.query.search as string || '';
    const status = req.query.status as string || '';
    const sortBy = req.query.sortBy as string || 'createdAt';
    const sortOrder = (req.query.sortOrder as string) === 'desc' ? -1 : 1;

    const skip = (page - 1) * limit;

    // Build query conditions
    const query: any = {};

    // Filter by user role
    const user = await User.findById(userId);
    if (!user) {
      return res.status(404).json({ success: false, error: 'User not found' });
    }

    if (user.role === 'regulator') {
      // Regulatory users can see all reports (for review)
      // No filtering conditions added
    } else if (user.role === 'manufacturer') {
      // Manufacturer users can only see reports they created
      query.createdBy = userId;
    }
    // Admin can see all reports

    // Add search conditions
    if (search) {
      query.$or = [
        { title: { $regex: search, $options: 'i' } },
        { description: { $regex: search, $options: 'i' } }
      ];
    }

    // Add status filter
    if (status) {
      query.status = status;
    }

    // Execute query
    const reports = await OrderReport.find(query)
      .populate('assignedTo', 'firstName lastName email role')
      .populate('createdBy', 'firstName lastName email role')
      .populate('orderId', 'batchNumber status producedQuantity')
      .sort({ [sortBy]: sortOrder })
      .skip(skip)
      .limit(limit);

    // Get total count
    const total = await OrderReport.countDocuments(query);

    // Calculate pagination info
    const totalPages = Math.ceil(total / limit);
    const hasNextPage = page < totalPages;
    const hasPrevPage = page > 1;

    res.json({
      success: true,
      data: reports,
      pagination: {
        currentPage: page,
        totalPages,
        totalItems: total,
        itemsPerPage: limit,
        hasNextPage,
        hasPrevPage
      },
      count: reports.length
    });
  } catch (err) {
    console.error('Get order reports error:', err);
    res.status(500).json({ success: false, error: 'Server error' });
  }
};

// Get single order report
// GET /order-reports/:id
export const getOrderReportById = async (req: RequestWithUser, res: Response) => {
  try {
    const { id } = req.params;
    const userId = (req as any).user?.id;

    if (!userId) {
      return res.status(401).json({ success: false, error: 'Unauthorized' });
    }

    const report = await OrderReport.findById(id)
      .populate('assignedTo', 'firstName lastName email role')
      .populate('createdBy', 'firstName lastName email role')
      .populate({
        path: 'orderId',
        populate: {
          path: 'createdBy',
          select: 'firstName lastName email'
        }
      });

    if (!report) {
      return res.status(404).json({ success: false, error: 'Order report not found' });
    }

    // Check permissions
    const user = await User.findById(userId);
    if (!user) {
      return res.status(404).json({ success: false, error: 'User not found' });
    }

    // Regulatory users can view all reports (for review)
    if (user.role === 'regulator') {
      // Allow all regulatory users to view reports
    }

    if (user.role === 'manufacturer' && report.createdBy._id.toString() !== userId) {
      return res.status(403).json({ success: false, error: 'Access denied' });
    }

    // Build response data with complete order information
    const responseData = {
      ...report.toObject(),
      orderDetails: report.orderId // Include complete order information
    };

    res.json({
      success: true,
      data: responseData
    });
  } catch (err) {
    console.error('Get order report by ID error:', err);
    res.status(500).json({ success: false, error: 'Server error' });
  }
};

// Update order report status
// PATCH /order-reports/:id/status
export const updateOrderReportStatus = async (req: RequestWithUser, res: Response) => {
  try {
    const { id } = req.params;
    const { status, comment } = req.body;
    const userId = (req as any).user?.id;

    if (!userId) {
      return res.status(401).json({ success: false, error: 'Unauthorized' });
    }

    // Validate status
    if (!['pending', 'approved', 'rejected'].includes(status)) {
      return res.status(400).json({ 
        success: false, 
        error: 'Invalid status. Must be pending, approved, or rejected' 
      });
    }

    const report = await OrderReport.findById(id);
    if (!report) {
      return res.status(404).json({ success: false, error: 'Order report not found' });
    }

    // Check permissions - only assigned regulatory users or admin can update status
    const user = await User.findById(userId);
    if (!user) {
      return res.status(404).json({ success: false, error: 'User not found' });
    }

    if (user.role !== 'admin' && user.role !== 'regulator') {
      return res.status(403).json({ success: false, error: 'Access denied' });
    }

    // If user is regulator, check if they are the assigned user
    if (user.role === 'regulator' && report.assignedTo.toString() !== userId) {
      return res.status(403).json({ 
        success: false, 
        error: 'Only the assigned regulator can update this report' 
      });
    }

    // Update report
    const updatedReport = await OrderReport.findByIdAndUpdate(
      id,
      { 
        status,
        ...(comment && { comment })
      },
      { new: true }
    ).populate('assignedTo', 'firstName lastName email role')
     .populate('createdBy', 'firstName lastName email role')
     .populate('orderId', 'batchNumber status producedQuantity');

    res.json({
      success: true,
      data: updatedReport,
      message: 'Order report status updated successfully'
    });
  } catch (err) {
    console.error('Update order report status error:', err);
    res.status(500).json({ success: false, error: 'Server error' });
  }
};

// Delete order report
export const deleteOrderReport = async (req: RequestWithUser, res: Response) => {
  try {
    const { id } = req.params;
    const userId = (req as any).user?.id;

    if (!userId) {
      return res.status(401).json({ success: false, error: 'Unauthorized' });
    }

    const report = await OrderReport.findById(id);
    if (!report) {
      return res.status(404).json({ success: false, error: 'Order report not found' });
    }

    // Check permissions - only creator or admin can delete
    const user = await User.findById(userId);
    if (!user) {
      return res.status(404).json({ success: false, error: 'User not found' });
    }

    if (user.role !== 'admin' && report.createdBy._id.toString() !== userId) {
      return res.status(403).json({ success: false, error: 'Access denied' });
    }

    await OrderReport.findByIdAndDelete(id);

    res.json({
      success: true,
      message: 'Order report deleted successfully'
    });
  } catch (err) {
    console.error('Delete order report error:', err);
    res.status(500).json({ success: false, error: 'Server error' });
  }
};

// Auto-create order report (called when order needs disposal)
export const autoCreateOrderReport = async (orderId: string, createdBy: string, disposalQuantity: number) => {
  try {
    console.log('Auto create order report called with:', { orderId, createdBy, disposalQuantity });
    
    // Find an available regulatory user
    const regulatoryUser = await User.findOne({ role: 'regulator' });
    if (!regulatoryUser) {
      console.error('No regulatory user found for order report assignment');
      return null;
    }
    console.log('Found regulatory user:', regulatoryUser._id);

    const order = await Order.findById(orderId);
    if (!order) {
      console.error('Order not found for report creation');
      return null;
    }
    console.log('Found order:', order.batchNumber);

    const report = await OrderReport.create({
      title: `Disposal Request: Order ${order.batchNumber}`,
      description: `Disposal request for order ${order.batchNumber}. Quantity: ${disposalQuantity}`,
      orderId,
      assignedTo: regulatoryUser._id,
      createdBy,
      disposalQuantity
    });

    console.log(`Order report created successfully: ${report._id}`);
    return report;
  } catch (err) {
    console.error('Auto create order report error:', err);
    return null;
  }
}; 